### ISSUE TITLE
Cannot add a parameter to From header

### ISSUE THREAD

**Issue by CelsoGalo** [davehorton/drachtio-srf#28]
Hey Dave! I hope you are fine!

I am trying to add a parameter (epid) to the From header when generating a REGISTER request. Somehow I cannot do it... I get a response "Error creating leg"

        srf.request(`sip:${phoneNumber}@localhost;transport=tcp`, {
            method: 'REGISTER',
            headers: {
                'contact': `<sip:${phoneNumber}@localhost>;transport=tcp`,
                'from': `<sip:${phoneNumber}@localhost>;tag=${fromTag};epid=${epid}`,
                'expires': expires
            }
        }

Do you know how I can do it? I searched but didn't find any documentation about it. Thanks!

**Comment by davehorton** [comment]
Hmm, can you share the drachtio server log when it processed that request?  Preferably with log level set to debug

One thing that looks a little strange is that you have the request-uri set to localhost....drachtio server will reject a request to send a message to itself (in order to avoid looping scenarios)

**Comment by CelsoGalo** [comment]
Oh... Sorry for the basic error. I restarted everything and fixed the R-URI, so it is working right now. Thanks!!

**Comment by davehorton** [comment]
OK great!  Ping me if you run into any other problems.
