### ISSUE TITLE
How to get the body of ACK?

### ISSUE THREAD

**Issue by calvet27** [davehorton/drachtio-srf#32]
Can I use [use] term of srf for catching ACK caused by INVITE? In such a 3rd party call control, I have to get SDP in received ACK method caused by reINVITE in dialog. Any suggestions?

**Comment by davehorton** [comment]
So it sounds like this is a user-agent server (uas) scenario?  You are receiving an INVITE without SDP, sending a 200 OK and then receiving the ACK?  Let me know if I have that right?

I'm also confused because you mentioned this is a re-INVITE.  I'm only used to seeing 3pcc INVITEs on the initial INVITE.  If this is a re-INVITE scenario, can you give me more details on what the initial INVITE looked like, and the re-INVITE?

**Comment by calvet27** [comment]
Thank you for reply. 

I mean that the case of getting ACK for 200 OK caused by reINVITE without in a dialog. I had to get the body of ACK because of this case; the first reINVITE has no SDP and then I should send offer SDP in 200 OK. 

Finally I found the solution. I just add the event listener for that dialog with a key, 'ack'. It works properly.

**Comment by davehorton** [comment]
OK, thanks.  That is an interesting use case -- receiving a 3pcc on re-INVITE.  I guess I will close this now since you have a solution (feel free to reopen if you feel otherwise)
