### ISSUE TITLE
setting Call-ID

### ISSUE THREAD

**Issue by amoonrah** [davehorton/drachtio-srf#53]
Hi there,

I'm starting a new UAC using the createUAC function, is there a way to set the call ID, the from and to tags.

also where can I find a list of the parameters that can be passed to that function.

I'm still fairly new to this, i apologize if the answer is on the site, I just wasn't able to find it, any help would be greatly appreciated.

**Comment by davehorton** [comment]
Usually people don't want to set the Call-ID, or tags....they will be set automatically by createUAC (well, by the drachtio server, really).

Do you have a specific need to see a specific value in either Call-Id or the from tag?  Its doable if you do, but dont want to have you spend time on something unnecessary

**Comment by amoonrah** [comment]
I don't really want to set them, but i'm going by some of the examples that I have seen, I'm trying to setup the RTP stream, and the function that talks to the rtpengine, seems to need some of that information.

 
   const details = {
    'call-id': 'nodjsapp',
    'from-tag': 'from.params.tag'
  };

    let mySDP = "v=0\r\no=user1 53655765 2353687637 IN IP4 192.168.194.63\r\ns=-\r\nc=IN IP4 192.168.194.63\r\nt=0 0\r\nm=audio 6000 RTP/AVP 0\r\na=rtpmap:0 PCMU/8000\r\n";


    RTPengine.offer(config.get('rtpengine'), Object.assign(details, {'sdp':mySDP,'ICE':'remove'}))
    .then((RTPResponse) => {

        srf.createUAC( 'sip:5555555555@somedomain.com', {
                        method: 'INVITE',
                        localSdp: RTPResponse.sdp,
                        headers: { From: 'sip:6666666666@somedomain.com' }
        })
        .then((dialog) => {
                console.log(dialog);
                dialog.on('destroy', () => {
                        console.log('called party ended call');
                        process.exit(1);
                });
        })
        .catch((err) => {
                console.log(`call failed with ${err.status}`);
        });
    })
    .catch((err) => {
        console.log(`Error: ${err}`);
    });

**Comment by davehorton** [comment]
Can you describe your scenario?  usually you have an inbound call when you connect the media through rtpengine.  Is your case different?  When you use createUAC you need to offer some sdp in the invite...what sort of media endpoint will be on the sending side of the connection?

**Comment by amoonrah** [comment]
i'm trying to create a simple outbound call ... I assumed that media would need to be handled by an external RTP server such as rtpengine.

**Comment by davehorton** [comment]
OK.  Definitely a bit of a strange use case for how you are using rtpengine.  I don't know that there is a good way to have rtpengine generate a media endpoint outside of/before a call, like you are wanting to do.  What you are doing -- making a fake sdp and feeding it to rtpengine _might_ work, but I cant guarantee it and will require additional re-invites/re-offers once the call is established.  You might want to ask a question in the rtpengine repo about whether what you want to do is possible with that product.  I use rtpengine a lot, but not in the way you are trying to.  When I need to do something like outdial from an IVR, I typically use freeswitch.

Anyways, let me stick to the specific question you asked me -- how to set a specific call-id and a specific tag on the From header of an INVITE you are sending.

You can specify sip headers using the `opts.headers` property of [Srf#createUAC](https://drachtio.org/api#srf-create-uac).

This even applies to the SIP Call-ID (again, in 99% of the use cases its easier to let the drachtio server create the Call-ID)

```
const uac = srf.createUAC(uri, {
  headers: {
    'Call-ID': 'my-fabulous-callid'
  }
});
```
You can even specify the tag on the From header like this:
```
const uac = srf.createUAC(uri, {
  headers: {
    'Call-ID': 'my-fabulous-callid',
   'From': 'tag=here-is-my-special-tag-value'
  }
});
```
The drachtio server will fill out the rest of the From value, or you should be able to put the entire From header in there.

Because this is a rare use case, I have not done a ton of testing on this, so if you find the above is not working let me know.  I'll keep the ticket open for now.

**Comment by amoonrah** [comment]
Yeah i've gone through some of the other repositories that you have and it seems "drachtio-fsmrf" may do the job.

I'm trying to create an app, where I can create two UACs that register each with their application server (different lines of business) and then exchange RTP, Testing the systems end to end.

thank you for you prompt replies.

**Comment by davehorton** [comment]
are you trying to create a test harness where these 2 UACs are testing a 3rd system in the middle?

**Comment by amoonrah** [comment]
exactly :)

**Comment by amoonrah** [comment]
your software sure beats using sipp for functional testing in many cases, it makes a huge difference when you have a full fledged programming language, with an engine like dracthio.

**Comment by davehorton** [comment]
sorry for the delay in responding.  You may want to look at this app as an example UAC I built for some testing:

https://github.com/davehorton/drachtio-conf-tester

**Comment by amoonrah** [comment]
oh no worry ... I've managed to create a very basic app that registers and waits for calls and another one that initiates calls, using the drachtio-fsmrf framework for media.

If you would like I can share them on here

**Comment by davehorton** [comment]
sure, if you would add a link to a gist, or otherwise share, that would be great!

**Comment by amoonrah** [comment]
https://gist.github.com/amoonrah/2307411f53bc2346598da777db8b8169
