### ISSUE TITLE
B2BUA Custom From Header

### ISSUE THREAD

**Issue by isaacpz** [davehorton/drachtio-srf#55]
Hi! I have a Drachtio B2BUA, and I'm trying to implement a caller-ID masking service, where the B2BUA alters the caller’s address in the From header to a different name & URI. 

I'm currently trying to implement this by using passing in a new `From` value to the `opts.headers` field in `createB2BUA`, but it seems like the B-leg is ignoring the new From header and using the same From header as the A-leg.

Is this functionality possible using Drachtio? Is using `opts.headers` the correct approach? Happy to upload the reproducing code if you think it's a problem with my implementation.

Thanks so much!

**Comment by davehorton** [comment]
yes, opts.headers should be the correct approach.  I think the issue was that originally some of the core sip headers like 'From' I was not letting you modify, over time I relaxed this but it seems like perhaps I did not allow this for the From header.  I will look into this.  Meanwhile, can you verify the version of drachtio-server you are running (`drachtio -v`)?

**Comment by isaacpz** [comment]
Would be **_awesome_** to allow that functionality for the From header. Pretty important for my use case. The server is using `drachtio-server:latest` from docker-hub, so should be `4.4.14`.

Thanks for your help!

**Comment by davehorton** [comment]
ok in my testing, it does look like I have a bug. Also, there is a workaround which I think should work for you.  In `opts.headers` instead of naming the property `From` name it `from` (lower-case).

i.e. this worked in my testing:
```
      const {uas, uac} = await srf.createB2BUA(req, res, config.get('dest'), {
        headers: {
          from: 'myname <sip:foo@localhost>'
        }
      });
```
The 'localhost' will be replaced with the local IP that drachtio is listening on.

Please let me know if this works for you.  Meanwhile I will check in a fix so that 'From' works as well..

**Comment by davehorton** [comment]
ok I pushed drachtio-srf@4.4.17 which should have the proper fix for this (either opts.From or opts.from should let you set a customized From header).  It would be great if you can confirm this works in your application.

**Comment by davehorton** [comment]
BTW, if all you wanted to do was set the user part of the From header on the outbound invite to something, another even simpler way to do that is:
```
const {uas, uac} = await srf.createB2BUA(req, res, config.get('dest'), {
         callingNumber: '+15083084809'
      });
```
But if you want to set the display name, etc, the use `opts.headers.From`.  Again, unless you have a specific need to set the host part of that sip url to something, I'd suggest setting it to 'localhost' and letting the server substitute appropriately

**Comment by davehorton** [comment]
can you confirm this works for you?

**Comment by isaacpz** [comment]
Yes works great! Thank you!
