### ISSUE TITLE
Prevent multiple attempts to send a response

### ISSUE THREAD

**Issue by rnewman** [davehorton/drachtio-srf#73]
Just noticed this. As far as I can tell, drachtio-srf allows code like this:

```
await res.send(200);
await res.send(400);
```

and either the second send silently fails, or it succeeds, which is also wrong.

I suspect this should be an error — `finished` is set to true here:

https://github.com/davehorton/drachtio-srf/blob/master/lib/response.js#L127

but not checked in `send`.

**Comment by davehorton** [comment]
Good catch.  In fixing it, I noticed that I was even calling it twice in a B2B cancel scenario!

Till now, doing so has been harmless because the drachtio server discards the second final response with a log message.  I was initially thinking res#send should throw an error when someone tries to send a second final response, but this may break some applications  that have been doing so (unknowingly), so I may just ignore any send after a final response has been sent.

**Comment by davehorton** [comment]
fixed in 4.4.28
