### ISSUE TITLE
Detecting timeout on connections

### ISSUE THREAD

**Issue by andgith** [davehorton/drachtio-srf#82]
What is the recommended way to detect a timeout on each side of a dialogue? For example one side disconnects without sending a BYE.

I have tried sending an UPDATE every few minutes but the handler does not seem to be getting a response.

Im using this to send the request on both UAS and UAC.

```
dlg.request({ 
    method: 'UPDATE'
  }, (err, req) => {
    console.log('Sending UPDATE)
    req.on('response', (res) => {
      console.log('received ${res.status} response to our UPDATE request');
    });
  });
```

Looking at the debug logs, the 200 OK is received but the `req.on` does not trigger.

Thank You

**Comment by davehorton** [comment]
sip session timers are the recommended way to detect if the remote side of a dialog has gone away without sending a BYE.

Sending the updates as you are doing are one part of it -- the other would be including a Session-Expires header on the initial INVITE that you send as UAC (or the 200 OK you send as UAS).

The docs are slightly wrong (I need to fix them)-- `dlg.request` will resolve with the response to the the request sent.  So try this instead:

```
dlg.request({ 
    method: 'UPDATE'
  }, (err, res) => {
    console.log(`received response to UPDATE with status ${res.status}`);
 });
```

**Comment by andgith** [comment]
Thank you, I have gotten that implementation working well. Sorry to ask another question in the issue but can you retrieve all the active dialogues from the drachtio server or do you need to maintain that in the client side?

**Comment by davehorton** [comment]
you would need to maintain them in your client side app, e.g. in a Map

**Comment by andgith** [comment]
That makes sense, I'll close the issue.

**Comment by davehorton** [comment]
One more comment on support for Session-Expires, for anyone coming on to this thread.

The idea is to not have to have your app be concerned with this - it should be taken care of the by the server. I am pushing some changes to the develop branch shortly that will do this, so that:

- as UAC, when you send an INVITE, just include a Session-Expires header.  The server will take it from there, as far as sending periodic re-INVITEs 
- as UAS, when responding to an INVITE offering Session-Expires, just include a Session-Expirs in yoor 200 OK.  Again, the server will handle things from there.
