### ISSUE TITLE
question on call forking

### ISSUE THREAD

**Issue by moonlitknight** [davehorton/drachtio-srf#86]
I want to fork an INVITE so it is passed to each of a user's registered devices to ring simultaneously (ie. a ring group, as opposed to a hunt group where the devices ring in turn).

The approach I'm taking is to iterate over the registered devices and call `srf.createB2BUA` on each of them. Before I go too far down this path, I want to check I'm barking up the right tree, and there isn't a simpler solution, e.g. something akin to Asterisk dialplan's `sip/ext100&sip/ext101&sip/ext102` or passing an array of uris to `srf.createB2BUA`.

A Meta question. Is a github issue the best way to ask questions? I'm happy to ask on stackoverflow and create a `drachtio` tag if that's a better way to connect to the drachtio community.

**Comment by davehorton** [comment]
yes, you are correct in your approach. You need to repeatedly call `srf.createB2BUA` on each destination, making sure to pass `opts.passFailure` as false, so that one failure does not propagate back to the incoming leg.  You need to collect all of the Promises returned and then wait for the first resolve, canceling the remaining calls in progress.

we actually created an implementation of this simring feature [here](https://github.com/davehorton/drachtio-fn-b2b-sugar) that you may be able to use.

Its fine to open questions on github for questions like these, I feel it helps others in the future who may have a similar question

**Comment by moonlitknight** [comment]
sweet
